language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    include:
        - php: 5.5
          env: DEPENDENCIES='low'
        - php: 5.6
          env: DEPENDENCIES='dev'
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*
    allow_failures:
        - env: DEPENDENCIES='dev'
    fast_finish: true

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - composer selfupdate
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
    - export SYMFONY_DEPRECATIONS_HELPER=weak
    - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$DEPENDENCIES" != "low" ]; then travis_retry composer update; fi;
    - if [ "$DEPENDENCIES" == "low" ]; then travis_retry composer update --prefer-lowest; fi;

script:
    - phpunit --configuration phpunit.xml.dist --verbose
